apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "valiant.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valiant.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
