apiVersion: v1
kind: Secret
metadata:
  name: valiant-db-credentials
  namespace: valiant
  labels:
    app.kubernetes.io/name: valiant-db-credentials
    app.kubernetes.io/part-of: valiant
type: Opaque
stringData:
  DATABASE_URL: "postgres://valiant:changeme@postgres.valiant.svc.cluster.local:5432/valiant?sslmode=disable"
  POSTGRES_PASSWORD: "changeme"
