apiVersion: v1
kind: ServiceAccount
metadata:
  name: valiant-backend
  namespace: valiant
  labels:
    app.kubernetes.io/name: valiant-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: valiant
